可达图节点共有6个
如下所示

0
(nondet_num_short,1,101 )    (__VERIFIER_error begin,0,)    (__VERIFIER_error end,0,)    (jump0,0,)    (__VERIFIER_nondet_short begin,0,)    (__VERIFIER_nondet_short end,0,)    (__VERIFIER_nondet_short_v,1,-842150451 )    (nondet_num_short=nondet_num_short-1,0,)    (jump2,0,)    (__VERIFIER_assert begin,0,)    (__VERIFIER_assert@cond,1,-842150451 )    (__VERIFIER_assert end,0,)    (sel0,0,)    (__VERIFIER_error(),0,)    (__VERIFIER_error()_c,0,)    (__VERIFIER_error_call,0,)    (jump3,0,)    (main begin,1,)    (fun5@y,1,1 )    (iter1,0,)    (iter1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=2,0,)    (__VERIFIER_assert(),0,)    (__VERIFIER_assert()_c,0,)    (__VERIFIER_assert_call#1,0,)    (iter1#1,0,)    (iter1#1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=3,0,)    
后继节点:1    经过变迁:T15    
1
(nondet_num_short,1,101 )    (__VERIFIER_error begin,0,)    (__VERIFIER_error end,0,)    (jump0,0,)    (__VERIFIER_nondet_short begin,0,)    (__VERIFIER_nondet_short end,0,)    (__VERIFIER_nondet_short_v,1,-842150451 )    (nondet_num_short=nondet_num_short-1,0,)    (jump2,0,)    (__VERIFIER_assert begin,0,)    (__VERIFIER_assert@cond,1,-842150451 )    (__VERIFIER_assert end,0,)    (sel0,0,)    (__VERIFIER_error(),0,)    (__VERIFIER_error()_c,0,)    (__VERIFIER_error_call,0,)    (jump3,0,)    (main begin,0,)    (fun5@y,1,1 )    (iter1,0,)    (iter1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=2,0,)    (__VERIFIER_assert(),0,)    (__VERIFIER_assert()_c,0,)    (__VERIFIER_assert_call#1,0,)    (iter1#1,0,)    (iter1#1 end,0,)    (__VERIFIER_nondet_short(),1,)    (__VERIFIER_nondet_short()_c,0,)    (y+=3,0,)    
后继节点:2    经过变迁:T38    
2
(nondet_num_short,1,101 )    (__VERIFIER_error begin,0,)    (__VERIFIER_error end,0,)    (jump0,0,)    (__VERIFIER_nondet_short begin,1,)    (__VERIFIER_nondet_short end,0,)    (__VERIFIER_nondet_short_v,1,-842150451 )    (nondet_num_short=nondet_num_short-1,0,)    (jump2,0,)    (__VERIFIER_assert begin,0,)    (__VERIFIER_assert@cond,1,-842150451 )    (__VERIFIER_assert end,0,)    (sel0,0,)    (__VERIFIER_error(),0,)    (__VERIFIER_error()_c,0,)    (__VERIFIER_error_call,0,)    (jump3,0,)    (main begin,0,)    (fun5@y,1,1 )    (iter1,0,)    (iter1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=2,0,)    (__VERIFIER_assert(),0,)    (__VERIFIER_assert()_c,0,)    (__VERIFIER_assert_call#1,0,)    (iter1#1,0,)    (iter1#1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=3,0,)    
后继节点:3    经过变迁:T5    
3
(nondet_num_short,1,101 )    (__VERIFIER_error begin,0,)    (__VERIFIER_error end,0,)    (jump0,0,)    (__VERIFIER_nondet_short begin,0,)    (__VERIFIER_nondet_short end,0,)    (__VERIFIER_nondet_short_v,1,-842150451 )    (nondet_num_short=nondet_num_short-1,1,)    (jump2,0,)    (__VERIFIER_assert begin,0,)    (__VERIFIER_assert@cond,1,-842150451 )    (__VERIFIER_assert end,0,)    (sel0,0,)    (__VERIFIER_error(),0,)    (__VERIFIER_error()_c,0,)    (__VERIFIER_error_call,0,)    (jump3,0,)    (main begin,0,)    (fun5@y,1,1 )    (iter1,0,)    (iter1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=2,0,)    (__VERIFIER_assert(),0,)    (__VERIFIER_assert()_c,0,)    (__VERIFIER_assert_call#1,0,)    (iter1#1,0,)    (iter1#1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=3,0,)    
后继节点:4    经过变迁:T6    
4
(nondet_num_short,1,100 )    (__VERIFIER_error begin,0,)    (__VERIFIER_error end,0,)    (jump0,0,)    (__VERIFIER_nondet_short begin,0,)    (__VERIFIER_nondet_short end,0,)    (__VERIFIER_nondet_short_v,1,-842150451 )    (nondet_num_short=nondet_num_short-1,0,)    (jump2,1,)    (__VERIFIER_assert begin,0,)    (__VERIFIER_assert@cond,1,-842150451 )    (__VERIFIER_assert end,0,)    (sel0,0,)    (__VERIFIER_error(),0,)    (__VERIFIER_error()_c,0,)    (__VERIFIER_error_call,0,)    (jump3,0,)    (main begin,0,)    (fun5@y,1,1 )    (iter1,0,)    (iter1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=2,0,)    (__VERIFIER_assert(),0,)    (__VERIFIER_assert()_c,0,)    (__VERIFIER_assert_call#1,0,)    (iter1#1,0,)    (iter1#1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=3,0,)    
后继节点:5    经过变迁:T7    
5
(nondet_num_short,1,100 )    (__VERIFIER_error begin,0,)    (__VERIFIER_error end,0,)    (jump0,0,)    (__VERIFIER_nondet_short begin,0,)    (__VERIFIER_nondet_short end,1,)    (__VERIFIER_nondet_short_v,1,100 )    (nondet_num_short=nondet_num_short-1,0,)    (jump2,0,)    (__VERIFIER_assert begin,0,)    (__VERIFIER_assert@cond,1,-842150451 )    (__VERIFIER_assert end,0,)    (sel0,0,)    (__VERIFIER_error(),0,)    (__VERIFIER_error()_c,0,)    (__VERIFIER_error_call,0,)    (jump3,0,)    (main begin,0,)    (fun5@y,1,1 )    (iter1,0,)    (iter1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=2,0,)    (__VERIFIER_assert(),0,)    (__VERIFIER_assert()_c,0,)    (__VERIFIER_assert_call#1,0,)    (iter1#1,0,)    (iter1#1 end,0,)    (__VERIFIER_nondet_short(),0,)    (__VERIFIER_nondet_short()_c,0,)    (y+=3,0,)    
后继节点:
